blog/urls.py
from django.urls import path
from django.views.defaults import page_not_found

from . import views

app_name = 'blog'
urlpatterns = [
    path('now/', views.NowView.as_view(), name='now'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('contact/', views.contact, name='contact'),
    path('post/<int:pk>', views.PostView.as_view(), name='post'),
    path('', views.main, name='main'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField('date created', auto_now=True)
    publication_date = models.DateTimeField(
        'date published', blank=True, null=True)
    views_count = models.IntegerField(default=0, blank=True)
    image_url = models.URLField(blank=True)
    tags = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

    def publish(self):
        self.publication_date = timezone.now()

    def is_published(self):
        return self.publication_date != None and self.publication_date <= timezone.now()
    is_published.boolean = True


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.shortcuts import redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.models import User
from django.views import generic
from django.views.defaults import page_not_found

from .models import Post


class NowView(generic.TemplateView):
    template_name = 'blog/now.html'


# @login_required
def main(request):
    # if not request.user.is_authenticated:
        # return page_not_found(request, "LOL:)")
     #   return redirect('{0}?next={1}'.format(settings.LOGIN_URL, request.path))

    #username = request.POST['username']
    #password = request.POST['password']
    #user = authenticate(request, username=username, password=password)
    #user = User.objects.all()[0]
    # if user:
        #login(request, user)

    return render(request, "blog/about.html")


class PostView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get_object(self):
        object = super().get_object()
        object.views_count += 1
        object.save()
        return object

    def get_queryset(self):
        return Post.objects.filter(publication_date__lte=timezone.now())


class PostsView(generic.ListView):
    template_name = 'blog/posts.html'
    model = Post

    context_object_name = 'posts'
    queryset = Post.objects.filter(
        publication_date__lte=timezone.now()).order_by('-publication_date')
    paginate_by = 10


def projects(request):
    return render(request, 'blog/projects.html')


def contact(request):
    return render(request, 'blog/contact.html')

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="https://getbootstrap.com/favicon.ico">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Bootstrap template for blog -->
  <link href="{% static 'blog/css/site-template.css' %}" rel="stylesheet"> {% block custom_head %}{% endblock %}

</head>

<body>

  {% block header %}
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'blog:main' %}">VK</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link {% if request.path|slice:" :4 " == '/now' %}active{% endif %}" href="{% url 'blog:now' %}">Now</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path|slice:" :6 " == '/posts' %}active{% endif %}" href="{% url 'blog:posts' %}">Posts</a>
        </li>
        <!--
        <li class="nav-item">
          <a class="nav-link {% if request.path|slice:" :8 " == '/contact' %}active{% endif %}" href="{% url 'blog:contact' %}">Contact</a>
</li>-->
      </ul>
    </div>
  </nav>
  {% endblock %} {% block content %}
  <main role="main" class="container">
    <div class="site-template">
      <h1>Bootstrap starter template</h1>
      <p class="lead">Use this document as a way to quickly start any new project.
        <br> All you get is this text and a mostly barebones HTML document.</p>
    </div>

  </main>
  <!-- /.container -->
  {% endblock %} {% block footer %}
  <hr>
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <br>
          <br>
          <p class="copyright text-muted">Copyright © Valeriy Kundas 2018</p>
        </div>
      </div>
    </div>
  </footer>
  {% endblock %}
</body>

</html>

blog/templates/blog/about.html
{% extends "base.html" %} {% block title %}About me{% endblock %} {% block content %}

<main role="main" class="container">
    <div class="site-template">
        <img src="https://avatars3.githubusercontent.com/u/11996384?s=400&u=7f0f3f536281e35944a2b505503e3341c7f51c02&v=4" alt="avatar"
            height="150vh">
        <h1>Valeriy Kundas</h1>
        <p class="lead">
            Human
            <br>Programmer
            <br>Environmentalist
        </p>
    </div>
</main>
{% endblock %} {% block active_about %}active{% endblock %}

blog/templates/blog/contact.html
{% extends 'base.html' %} {% load static %} {% block title %}Contact{% endblock %} {% block custom_head %}
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Clean Blog - Start Bootstrap Theme</title>

{% endblock %} {% block content %}

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
      <br>
      <form name="sentMessage" id="contactForm" novalidate="">
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <input class="form-control" placeholder="Name" id="name" required="" data-validation-required-message="Please enter your name."
              type="text">
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <input class="form-control" placeholder="Email Address" id="email" required="" data-validation-required-message="Please enter your email address."
              type="email">
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <input class="form-control" placeholder="Phone Number" id="phone" required="" data-validation-required-message="Please enter your phone number."
              type="tel">
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <textarea rows="5" class="form-control" placeholder="Message" id="message" required="" data-validation-required-message="Please enter a message."></textarea>
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/main.html
{% extends "base.html" %}

{% block title %}Hello!{% endblock %}


blog/templates/blog/now.html
{% extends "base.html" %} {% block custom_head %}
<style>
    main a {
        text-decoration: underline;
        color: #000000;
    }
</style>
{% endblock %} {% block title %}About me{% endblock %} {% block content %}

<main role="main" class="container" style="margin: auto; width:30%; height: 300px">
    <br>
    <span class="lead">What I am doing now:</span>
    <br>
    <ul>
        <li>Studying:
            <a href="http://cs231n.stanford.edu/">cs231n</a>,
            <a href="https://www.youtube.com/playlist?list=PLrCZzMib1e9pg7ZLIOhmGSlmkMf8yEOLZ">Django</a>,
            <a href="https://www.commonlounge.com/discussion/5d2822257dfa49328d85fd27cf114441">algorithms</a>
        </li>
        <li>Doing sports: running, pull ups, martial arts</li>
        <li>Meditation</li>
        <li>Socializing</li>
        <li>Sleeping</li>
    </ul>
    <br>
    <span style="font-size: 80%">Last update: June 23, 2018</span>
</main>
{% endblock %} {% block active_about %}active{% endblock %}

blog/templates/blog/post.html
{% extends "base.html" %} {% load static %} {% block custom_head %}

<!-- Custom styles for this template -->
<link href="{% static 'blog/css/blog-post.css' %}" rel="stylesheet"> {% endblock %} {% block title %}{{ post.title }}{% endblock %} {% block content %}
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4">{{ post.title }}</h1>

      <!-- Author -->
      <p class="lead">
        by
        <a href="#">{{ post.author }}</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>Posted on {{ post.publication_date|date:"M d, Y" }}</p>

      <hr>

      <!-- Preview Image -->
      <img class="img-fluid rounded" src="{{ post.image_url }}" alt="">

      <hr>

      <!-- Post Content -->
      {{ post.text }}

      <hr>

      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
          <form>
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>

      <!-- Single Comment -->
      <!-- hidden -->
      <div class="media mb-4 d-none">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in
          vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis
          in faucibus.
        </div>
      </div>

      <!-- Comment with nested comments -->
      <!-- hidden -->
      <div class="media mb-4 d-none">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in
          vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis
          in faucibus.

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in
              vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue
              felis in faucibus.
            </div>
          </div>

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in
              vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue
              felis in faucibus.
            </div>
          </div>

        </div>
      </div>

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <!-- hidden -->
      <div class="card my-4 d-none">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <!--<div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    -->

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">About me</h5>
        <div class="card-body">
          <a href="https://www.instagram.com/valeriykundas/">My instagram</a>
        </div>
      </div>

    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

blog/templates/blog/posts.html
{% extends 'base.html' %} {% load static %} {% block title %}Posts{% endblock %} {% block custom_head %}

<!-- Custom styles for this template -->
<link href="{% static 'blog/css/blog-home.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<!-- Page Content -->
<div class="container">
  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

      <h1 class="my-4">
        Occasional writings
      </h1>

      <!-- Blog Post -->
      {% if not posts %}
      <main role="main" class="container">

        <div class="site-template">
          <br>
          <p class="lead">There are no posts yet...</p>
        </div>
      </main>
      <!-- /.container -->
      {% else %} {% for post in object_list %}
      <div class="card mb-4">
        <img class="card-img-top" src="{{ post.image_url }}">
        <div class="card-body">
          <h2 class="card-title">{{ post.title }}</h2>
          <p class="card-text">{{ post.text|truncatechars:270 }}</p>
          <a href="{% url 'blog:post' post.id %}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          Posted on {{ post.publication_date|date:"M d, Y" }} by
          <a href="#">{{ post.author }}</a>
        </div>
      </div>
      {% endfor %} {% endif %}

      <!-- Pagination -->
      <ul class="pagination justify-content-center mb-4">
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %} ">
          <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">&larr; Older</a>
        </li>
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
          <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">Newer &rarr;</a>
        </li>
      </ul>
    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4 d-none">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <!--<div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>-->

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">About me</h5>
        <div class="card-body">
          Here is my
          <a href="https://www.instagram.com/valeriykundas">Instagram</a>
        </div>
      </div>

    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

blog/templates/blog/projects.html
{% extends 'base.html' %}

{% block content %}
<div>
    here will be my projects
</div>
{% endblock %}